# Generated by Django 2.0.8 on 2018-11-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='flag',
            field=models.CharField(max_length=20),
        ),
    ]
